### PR TITLE
Create sv.json

### PR DESCRIPTION
**Pull request by tinwe**
Updating the swedish translation with further coherence to Free League's official character sheet translations

## Summary

Updating the swedish translation with further coherence to Free League's official character sheet translations

### PR Type

- [X] This PR is a code change that implements a feature request.
- [ ] This PR fixes an issue.
- [ ] This PR adds a new feature that is not an open feature request.
- [ ] This PR is not a code change (e.g. documentation, README, ...)
### Other
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] If code changes were made then they have been tested.
- [ ] I have updated the documentation to reflect the changes (wiki).

### CODE REVIEW

**Comment by Stefouch** [comment]
Hi !

Thank you for the translation. You'll make many swedish players very happy.
I'll accept this PR as soon as the game is up-to-date for V9 (very soon).

**Comment by Stefouch** [comment]
Can you take a look at the `en.json` because I have added a few more entries ?

**Comment by tinwe** [comment]
> Can you take a look at the `en.json` because I have added a few more entries ?

Sure, but can you guide me how I create an update to the repository without creating yet another branch? I'm lost in this Github. Or should I email the file directly to you?

**Comment by Stefouch** [comment]
If it's too complex for you, you can send me the file of course.
Otherwise, to update your fork, here is the process:

### How to Update a Fork in Github

1. Access your forked repository on Github.
2. Click “Pull Requests” on the right, then click the “New Pull Request” button.
Github first compares the base fork with yours, and will find nothing if you made no changes, so, click “**switching the base**” (below), which will change your fork to the base, and the original to the head fork. Now you should see changes where your fork needs to play “catch up”.
3. Click “Create Pull Request”, give it a name, click “Send Pull Request”.
4. Click “Merge Pull Request” and “Confirm Merge”.

**Comment by tinwe** [comment]
Could you tell me what phrases are missing? Or at least what new phrases that has been added. 
The new file is of a completely different structure, but the old one still seems to work for me in 2.0.1

**Comment by Stefouch** [comment]
I have modified the file to took like the new 2.0 english version and added the 24 missing keys (they are in english).

Could you translate them ?

**Comment by Stefouch** [comment]
This can show you the difference : https://github.com/Stefouch/t2k4e/pull/74/commits/1a0e2c24d14125bfe23aa3c8ff0b4c792917a942

**Comment by tinwe** [comment]
> 

Thanks. I've translated the new phrases, but I'm sorry - I have no clue what so ever how to commit changes on Github.

Here's the modified code however;

`{
  "T2K4E.SheetClassCharacter": "Karaktärsblad",
  "T2K4E.SheetClassVehicle": "Fordonsblad",
  "T2K4E.SheetClassUnit": "Enhetsblad",
  "T2K4E.Attribute": "Grundegenskap",
  "T2K4E.Attributes": "Grundegenskaper",
  "T2K4E.AttributeNames.str": "Styrka",
  "T2K4E.AttributeNames.agl": "Smidighet",
  "T2K4E.AttributeNames.int": "Intelligens",
  "T2K4E.AttributeNames.emp": "Karisma",
  "T2K4E.Skill": "Färdighet",
  "T2K4E.Skills": "Färdigheter",
  "T2K4E.SkillNames.none": "–",
  "T2K4E.SkillNames.heavyWeapons": "Tunga vapen",
  "T2K4E.SkillNames.closeCombat": "Närstrid",
  "T2K4E.SkillNames.stamina": "Tålighet",
  "T2K4E.SkillNames.driving": "Fordon",
  "T2K4E.SkillNames.mobility": "Rörlighet",
  "T2K4E.SkillNames.rangedCombat": "Skytte",
  "T2K4E.SkillNames.recon": "Spaning",
  "T2K4E.SkillNames.survival": "Överlevnad",
  "T2K4E.SkillNames.tech": "Teknik",
  "T2K4E.SkillNames.command": "Befälskap",
  "T2K4E.SkillNames.persuasion": "Övertalning",
  "T2K4E.SkillNames.medicalAid": "Vård",
  "T2K4E.Action": "Handling",
  "T2K4E.Actions": "Handlingar",
  "T2K4E.ActionNames.unarmedAttack": "Oväpnad attack",
  "T2K4E.ActionNames.meleeAttack": "Attack med närstridsvapen",
  "T2K4E.ActionNames.grapple": "Håll fast",
  "T2K4E.ActionNames.breakFree": "Bryt dig loss",
  "T2K4E.ActionNames.shootFirearm": "Avfyra vapen",
  "T2K4E.ActionNames.clearJam": "Rensa vapenstopp",
  "T2K4E.ActionNames.aimSniper": "Prickskyttssiktande",
  "T2K4E.ActionNames.shootBow": "Avfyra båge",
  "T2K4E.ActionNames.throwWeapon": "Kasta vapnet",
  "T2K4E.ActionNames.aimMortar": "Sikta mortel eller haubits",
  "T2K4E.ActionNames.shootHeavyWeapon": "Avfyra tungt vapen",
  "T2K4E.ActionNames.firstAid": "Första hjälpen",
  "T2K4E.ActionNames.rally": "Återhämtning",
  "T2K4E.ActionNames.directFire": "Indirekt eldgivning",
  "T2K4E.ActionNames.seekCover": "Sök skydd",
  "T2K4E.ActionNames.run": "Spring",
  "T2K4E.ActionNames.crawl": "Kräla",
  "T2K4E.ActionNames.shove": "Fäll",
  "T2K4E.ActionNames.disarm": "Avväpna",
  "T2K4E.ActionNames.retreat": "Reträtt",
  "T2K4E.ActionNames.aim": "Sikta",
  "T2K4E.ActionNames.prepareBow": "Förbered båge",
  "T2K4E.ActionNames.overwatch": "Anta Övervakningsläge",
  "T2K4E.ActionNames.reload": "Ladda om",
  "T2K4E.ActionNames.drive": "Kör",
  "T2K4E.Constants": "Konstanter",
  "T2K4E.ConstantNames.encumbrance": "Belastning",
  "T2K4E.ConstantNames.awareness": "Stridsmedvetenhet",
  "T2K4E.ConstantNames.cuf": "Stridsvana",
  "T2K4E.TravelTasks": "Reseuppdrag",
  "T2K4E.TravelTaskNames.marching": "Marcherar",
  "T2K4E.TravelTaskNames.driving": "Kör",
  "T2K4E.TravelTaskNames.gathering": "Samlar",
  "T2K4E.TravelTaskNames.keepingWatch": "Vaktar",
  "T2K4E.TravelTaskNames.scrounging": "Plundrar",
  "T2K4E.TravelTaskNames.foraging": "Söker föda",
  "T2K4E.TravelTaskNames.hunting": "Jagar",
  "T2K4E.TravelTaskNames.fishing": "Fiskar",
  "T2K4E.TravelTaskNames.makingCamp": "Slår upp läger",
  "T2K4E.TravelTaskNames.cooking": "Lagar mat",
  "T2K4E.TravelTaskNames.resting": "Vilar",
  "T2K4E.TravelTaskNames.sleeping": "Sover",
  "T2K4E.TravelTaskNames.exploring": "Utforskar",
  "T2K4E.ArmorLocationNames.head": "Huvud",
  "T2K4E.ArmorLocationNames.arms": "Armar",
  "T2K4E.ArmorLocationNames.torso": "Bål",
  "T2K4E.ArmorLocationNames.legs": "Ben",
  "T2K4E.ConditionNames.starving": "Utsvulten",
  "T2K4E.ConditionNames.dehydrated": "Uttorkad",
  "T2K4E.ConditionNames.sleepless": "Sömnlös",
  "T2K4E.ConditionNames.hypothermic": "Nedkyld",
  "T2K4E.InjuryCategoryNames.physical": "Fysisk",
  "T2K4E.InjuryCategoryNames.mental": "Mental",
  "T2K4E.ActionTypes.fast": "Snabb",
  "T2K4E.ActionTypes.slow": "Långsam",
  "T2K4E.Ranges.close": "I närstrid",
  "T2K4E.Ranges.short": "Kort",
  "T2K4E.Ranges.medium": "Medel",
  "T2K4E.Ranges.long": "Lång",
  "T2K4E.Ranges.extreme": "Extrem",
  "T2K4E.ItemTypes.ammunition": "Ammunition",
  "T2K4E.ItemTypes.armor": "Kroppsskydd",
  "T2K4E.ItemTypes.gear": "Utrustning",
  "T2K4E.ItemTypes.grenade": "Sprängämne",
  "T2K4E.ItemTypes.injury": "Skada",
  "T2K4E.ItemTypes.specialty": "Specialitet",
  "T2K4E.ItemTypes.weapon": "Vapen",
  "T2K4E.ItemPropNames.twoHanded": "Tvåhandad",
  "T2K4E.ItemPropNames.mounted": "Monterad",
  "T2K4E.ItemPropNames.disposable": "Engångs",
  "T2K4E.ItemPropNames.ammoBelt": "Ammunitionsbälte",
  "T2K4E.ItemPropNames.magazine": "Är Magasin",
  "T2K4E.ItemPropNames.armored": "Bepansrad",
  "T2K4E.ItemPropNames.bipod": "Tvåbensstativ",
  "T2K4E.ItemPropNames.tripod": "Trebensstativ",
  "T2K4E.ItemPropNames.scope": "Kikarsikte",
  "T2K4E.ItemPropNames.nightVision": "Mörkerkikare",
  "T2K4E.ItemPropNames.bayonet": "Bajonett",
  "T2K4E.ItemPropNames.suppressor": "Ljuddämpare",
  "T2K4E.ActorTypes.character": "Rollperson (RP)",
  "T2K4E.ActorTypes.npc": "Spelarledarperson (SLP)",
  "T2K4E.ActorTypes.vehicle": "Fordon",
  "T2K4E.ActorSheet.Name": "Namn",
  "T2K4E.ActorSheet.MainTab": "Grund",
  "T2K4E.ActorSheet.CombatTab": "Strid",
  "T2K4E.ActorSheet.EquipmentTab": "Utrustning",
  "T2K4E.ActorSheet.BiographyTab": "Biografi",
  "T2K4E.ActorSheet.NoteTab": "Anteckning",
  "T2K4E.ActorSheet.Nationality": "Nationalitet",
  "T2K4E.ActorSheet.Branch": "Bransch",
  "T2K4E.ActorSheet.MilitaryRank": "Militär grad",
  "T2K4E.ActorSheet.HitCapacity": "Skada",
  "T2K4E.ActorSheet.StressCapacity": "Stress",
  "T2K4E.ActorSheet.CapacityModifier": "Modifierare:",
  "T2K4E.ActorSheet.Experience": "Erfarenhet",
  "T2K4E.ActorSheet.ExperienceCurrent": "Aktuell EP",
  "T2K4E.ActorSheet.ExperienceTotal": "Total EP",
  "T2K4E.ActorSheet.Appearance": "Utseende",
  "T2K4E.ActorSheet.MoralCode": "Personlig moral",
  "T2K4E.ActorSheet.Buddy": "Kamrat",
  "T2K4E.ActorSheet.BigDream": "Min stora dröm",
  "T2K4E.ActorSheet.GroupMeeting": "Hur jag mötte gruppen:",
  "T2K4E.ActorSheet.AttributesAndSkills": "Grundegenskaper & Färdigheter",
  "T2K4E.ActorSheet.Rating": "Värde",
  "T2K4E.ActorSheet.BaseDie": "Tärning",
  "T2K4E.ActorSheet.Specialties": "Specialiteter",
  "T2K4E.ActorSheet.AddSpecialty": "Lägg till en ny specialitet",
  "T2K4E.ActorSheet.NoSpecialty": "Denna karaktär har ingen specialitet. Klicka på \"+\" för att lägga till en specialitet.",
  "T2K4E.ActorSheet.Combat": "Strid",
  "T2K4E.ActorSheet.Actions": "Handlingar",
  "T2K4E.ActorSheet.Current": "Nu",
  "T2K4E.ActorSheet.Max": "Max",
  "T2K4E.ActorSheet.CuF": "Stridsvana",
  "T2K4E.ActorSheet.UnitMorale": "Stridsmoral",
  "T2K4E.ActorSheet.NoArmor": "Den här karaktären har inget utrustat kropssskydd.",
  "T2K4E.ActorSheet.Conditions": "Tillstånd",
  "T2K4E.ActorSheet.CriticalInjuries": "Kritisk skada",
  "T2K4E.ActorSheet.AddInjury": "Lägg till ny sjukdom",
  "T2K4E.ActorSheet.InjuryTimeLeft": "{time} kvar",
  "T2K4E.ActorSheet.Diseases": "Sjukdomar",
  "T2K4E.ActorSheet.Radiation": "Strålning",
  "T2K4E.ActorSheet.RadiationRoll": "Strålningsslag",
  "T2K4E.ActorSheet.TemporaryRadiation": "Tillfällig",
  "T2K4E.ActorSheet.PermanentRadiation": "Permanent",
  "T2K4E.ActorSheet.EncumbranceFull": "FULL",
  "T2K4E.ActorSheet.EncumbranceTooHeavy": "FÖR TUNG",
  "T2K4E.ActorSheet.Weapons": "Vapen",
  "T2K4E.ActorSheet.AddWeapon": "Lägg till nytt vapen",
  "T2K4E.ActorSheet.Unarmed": "Obeväpnad",
  "T2K4E.ActorSheet.Cover": "Skydd",
  "T2K4E.ActorSheet.Add": "Lägg till",
  "T2K4E.ActorSheet.AddArmor": "Lägg till nytt kroppsskydd",
  "T2K4E.ActorSheet.AddGear": "Lägg till ny utrustning",
  "T2K4E.ActorSheet.AddAmmo": "Lägg till ny ammunition",
  "T2K4E.ActorSheet.Encumbrance": "Belastning",
  "T2K4E.ActorSheet.CombatGearEncumbrance": "Stridsutrustning (Belastning)",
  "T2K4E.ActorSheet.BackpackEncumbrance": "Ryggsäck (Belastning)",
  "T2K4E.ActorSheet.Equip": "Utrusta",
  "T2K4E.ActorSheet.Store": "Lagra i ryggsäck",
  "T2K4E.ActorSheet.Edit": "Ändra",
  "T2K4E.ActorSheet.Delete": "Radera",
  "T2K4E.ActorSheet.NewItem.weapon": "Nytt vapen",
  "T2K4E.ActorSheet.NewItem.armor": "Nytt kroppsskydd",
  "T2K4E.ActorSheet.NewItem.gear": "Ny utrustning",
  "T2K4E.ActorSheet.NewItem.ammunition": "Ny ammunition",
  "T2K4E.ActorSheet.NewItem.specialty": "Ny specialitet",
  "T2K4E.ActorSheet.NewItem.injury": "Ny skada",
  "T2K4E.ActorSheet.NotifWrongItemType": "\"{type}\" föremål kan inte läggas till en {actor}!",
  "T2K4E.VehicleSheet.CrewTab": "Besättning",
  "T2K4E.VehicleSheet.ComponentsTab": "Komponenter",
  "T2K4E.VehicleSheet.CombatTab": "Stridande",
  "T2K4E.VehicleSheet.CargoTab": "Last",
  "T2K4E.VehicleSheet.VehicleType": "Fordonstyp",
  "T2K4E.VehicleSheet.Reliability": "Pålitlighet",
  "T2K4E.VehicleSheet.Movement": "Förflyttning",
  "T2K4E.VehicleSheet.CombatSpeed": "Stridshastighet",
  "T2K4E.VehicleSheet.TravelSpeed": "Reshastighet",
  "T2K4E.VehicleSheet.Wheels": "Hjul",
  "T2K4E.VehicleSheet.Tracks": "Band",
  "T2K4E.VehicleSheet.Hovercraft": "Svävare",
  "T2K4E.VehicleSheet.Flying": "Flygande",
  "T2K4E.VehicleSheet.Naval": "Marin",
  "T2K4E.VehicleSheet.Fuel": "Bränsle",
  "T2K4E.VehicleSheet.FuelCapacity": "Bränsletank",
  "T2K4E.VehicleSheet.FuelConsumption": "Bränsleförbrukning",
  "T2K4E.VehicleSheet.Gasoline": "Bensin",
  "T2K4E.VehicleSheet.Diesel": "Diesel",
  "T2K4E.VehicleSheet.Alcohol": "Alkohol",
  "T2K4E.VehicleSheet.Nuclear": "Kärnreaktor",
  "T2K4E.VehicleSheet.CrewQty": "Besättning:",
  "T2K4E.VehicleSheet.PassengerQty": "Passagerare:",
  "T2K4E.VehicleSheet.EmptyCrew": "Dra och släpp en aktör för att göra dem till besättning.",
  "T2K4E.VehicleSheet.Armor": "Pansar",
  "T2K4E.VehicleSheet.FrontArmor": "Front",
  "T2K4E.VehicleSheet.SideLeftArmor": "Vänster",
  "T2K4E.VehicleSheet.SideRightArmor": "Höger",
  "T2K4E.VehicleSheet.RearArmor": "Bak",
  "T2K4E.VehicleSheet.Damage": "Skada",
  "T2K4E.VehicleSheet.MountedWeapons1": "Primära vapen",
  "T2K4E.VehicleSheet.MountedWeapons2": "Sekundära vapen",
  "T2K4E.VehicleSheet.MountedWeaponType": "Typ",
  "T2K4E.VehicleSheet.CargoCapacity": "Lastvikt:",
  "T2K4E.VehicleSheet.CrewCargo": "Besättningsvikt:",
  "T2K4E.VehicleSheet.VehicleEncumbrance": "Belastning (fordon)",
  "T2K4E.VehicleSheet.Mount": "Montera vapen",
  "T2K4E.VehicleSheet.Unmount": "Avmontera vapen",
  "T2K4E.VehicleSheet.MoveMount": "Växla vapenfäste",
  "T2K4E.VehicleSheet.Price": "Pris",
  "T2K4E.VehicleSheet.CrewPositions.Driver": "FÖRARE",
  "T2K4E.VehicleSheet.CrewPositions.Gunner": "SKYTT",
  "T2K4E.VehicleSheet.CrewPositions.Commander": "BEFÄLHAVARE",
  "T2K4E.VehicleSheet.CrewPositions.Passenger": "PASSAGERARE",
  "T2K4E.VehicleSheet.ExposedPassenger": "Oskyddad",
  "T2K4E.VehicleSheet.InnerComponents": "Inre komponent",
  "T2K4E.VehicleSheet.OuterComponents": "Yttre komponent",
  "T2K4E.VehicleSheet.ComponentDamage": "Antal skada orsakad till denna komponent",
  "T2K4E.VehicleSheet.FcsType": "Typ",
  "T2K4E.VehicleSheet.Components.fuel": "Bränsle",
  "T2K4E.VehicleSheet.Components.engine": "Motor",
  "T2K4E.VehicleSheet.Components.suspension": "Nedhållande",
  "T2K4E.VehicleSheet.Components.ammunition": "Ammunition",
  "T2K4E.VehicleSheet.Components.radio": "Radio",
  "T2K4E.VehicleSheet.Components.trackWheel": "Band / Hjul",
  "T2K4E.VehicleSheet.Components.fcs": "Fire Control System",
  "T2K4E.VehicleSheet.Components.antenna": "Antenn",
  "T2K4E.VehicleSheet.HasTrailer": "Har ett släp",
  "T2K4E.VehicleSheet.HasSmokeDischarger": "Rökkastare",
  "T2K4E.UnitSheet.Name": "Fullständigt namn",
  "T2K4E.UnitSheet.Info": "Ytterligare information",
  "T2K4E.UnitSheet.Faction": "Fraktion",
  "T2K4E.UnitSheet.UnitAffiliation": "Tillhörighet",
  "T2K4E.UnitSheet.UnitSize": "Enhetsstorlek",
  "T2K4E.UnitSheet.UnitType": "Enhetstyp",
  "T2K4E.UnitSheet.UnitModifiers": "Enhetsmodifierare",
  "T2K4E.UnitSheet.Personnel": "Personal",
  "T2K4E.UnitSheet.Vehicles": "Stridsfordon",
  "T2K4E.UnitSheet.HQ": "Högvarter (HQ)",
  "T2K4E.UnitAffiliationNames.friendly": "Vänlig",
  "T2K4E.UnitAffiliationNames.hostile": "Fientlig",
  "T2K4E.UnitAffiliationNames.neutral": "Neutral",
  "T2K4E.UnitAffiliationNames.unknown": "Okänd",
  "T2K4E.UnitModifierNames.airborne": "Luftburen",
  "T2K4E.UnitModifierNames.parachute": "Fallskärm",
  "T2K4E.UnitModifierNames.airmobile": "Luftmobil",
  "T2K4E.UnitModifierNames.airmobileOrganicLift": "Airm. O. L.",
  "T2K4E.UnitModifierNames.amphibious": "Ampfibisk",
  "T2K4E.UnitModifierNames.motorized": "Motoriserad",
  "T2K4E.UnitModifierNames.moutain": "Berg",
  "T2K4E.UnitModifierNames.cannon": "Kanon",
  "T2K4E.UnitModifierNames.wheeled": "På hjul",
  "T2K4E.UnitSizeNames.army": "Armé XXXX",
  "T2K4E.UnitSizeNames.corps": "Corps XXX",
  "T2K4E.UnitSizeNames.division": "Division XX",
  "T2K4E.UnitSizeNames.Brigade": "Brigad X",
  "T2K4E.UnitSizeNames.regiment": "Regimente | | |",
  "T2K4E.UnitSizeNames.battalion": "Bataljon | |",
  "T2K4E.UnitSizeNames.company": "Kompani |",
  "T2K4E.UnitSizeNames.staffel": "Staffel ••••",
  "T2K4E.UnitSizeNames.platoon": "Pluton •••",
  "T2K4E.UnitSizeNames.section": "Sektion ••",
  "T2K4E.UnitSizeNames.squad": "Tropp •",
  "T2K4E.UnitSizeNames.fireteam": "Grupp",
  "T2K4E.ItemSheet.Name": "Namn",
  "T2K4E.ItemSheet.FeaturesTab": "Funktioner",
  "T2K4E.ItemSheet.ModifiersTab": "Modifierare",
  "T2K4E.ItemSheet.RollModifiers": "Slå modifierare",
  "T2K4E.ItemSheet.AddNewRollModifier": "Lägg till en ny tärningsmodifierare till detta föremål",
  "T2K4E.ItemSheet.DeleteRollModifier": "Ta bort denna tärningsmodifierare",
  "T2K4E.ItemSheet.NoRollModifier": "Detta föremål har ingen tärningsmodifierare. För att lägga till en, klicka på \"+\" ikonen.",
  "T2K4E.ItemSheet.SelectRollModifier": "Ange namn",
  "T2K4E.ItemSheet.DescriptionTab": "Anteckningar",
  "T2K4E.ItemSheet.AttributeUsed": "Grundegenskap använd",
  "T2K4E.ItemSheet.SkillUsed": "Färdighet använd",
  "T2K4E.ItemSheet.WeaponMagazine": "Magasin",
  "T2K4E.ItemSheet.Quantity": "Antal",
  "T2K4E.ItemSheet.ItemType": "Typ",
  "T2K4E.ItemSheet.Ammo": "Ammunition",
  "T2K4E.ItemSheet.AmmoType": "Ammunitionsidentifierare",
  "T2K4E.ItemSheet.OverrideOption": "Åsidosätt vapnets funktioner",
  "T2K4E.ItemSheet.Reliability": "Pål.",
  "T2K4E.ItemSheet.RoF": "Eldh.",
  "T2K4E.ItemSheet.Damage": "Skada",
  "T2K4E.ItemSheet.Crit": "Krit.",
  "T2K4E.ItemSheet.Blast": "Radie",
  "T2K4E.ItemSheet.Range": "Räckv.",
  "T2K4E.ItemSheet.Mag": "Mag.",
  "T2K4E.ItemSheet.Armor": "Skydd",
  "T2K4E.ItemSheet.Weight": "Vikt",
  "T2K4E.ItemSheet.Price": "Pris",
  "T2K4E.ItemSheet.ArmorLocation": "Skyddat område",
  "T2K4E.ItemSheet.Equipped": "Utrustad",
  "T2K4E.ItemSheet.StoredInBackpack": "Förvarad i ryggsäck",
  "T2K4E.ItemSheet.CreateAmmo": "Generera ammunition",
  "T2K4E.ItemSheet.CreateAmmoNotif": "Genererade 1x <b>{ammo}</b> för vapnet <b>{weapon}</b>",
  "T2K4E.ItemSheet.FeaturesForVehicle": "Fordonsegenskaper",
  "T2K4E.InjurySheet.Category": "Kategori",
  "T2K4E.InjurySheet.Location": "Plats",
  "T2K4E.InjurySheet.TimeLimit": "Tidsbegränsning",
  "T2K4E.InjurySheet.HealTime": "Heal Time",
  "T2K4E.InjurySheet.Effect": "Effekt",
  "T2K4E.InjurySheet.Lethal": "Dödlig",
  "T2K4E.InjurySheet.day": "dag",
  "T2K4E.InjurySheet.days": "dagar",
  "T2K4E.Chat.Actions.Attack": "Attackera",
  "T2K4E.Chat.Actions.Reload": "Ladda om",
  "T2K4E.Chat.Actions.Roll": "Slå",
  "T2K4E.Chat.Actions.Push": "Pressa",
  "T2K4E.Chat.Actions.ApplyDamage": "Applicera skada",
  "T2K4E.Chat.Roll.Success": "Lyckat",
  "T2K4E.Chat.Roll.Successes": "Lyckade",
  "T2K4E.Chat.Roll.Pushed": "— Pressat",
  "T2K4E.Chat.Roll.Suppression": "Nedhållen",
  "T2K4E.Chat.Roll.ExtraHit": "Extra träff",
  "T2K4E.Chat.Roll.ExtraHits": "Extra träffar",
  "T2K4E.Chat.Roll.Mishap": "Missöde",
  "T2K4E.Chat.Roll.AmmoSpent": "Använd ammunition",
  "T2K4E.Chat.Roll.NoItemNotif": "Detta föremål existerar inte längre.",
  "T2K4E.Chat.Roll.NoReliabilityNotif": "Föremålets nuvarande tillförlitlighet gör föremålet obrukbart.",
  "T2K4E.Chat.Damage.Incapacited": "OSKADLIGGJORD",
  "T2K4E.Chat.Damage.DamagedArmor": "Skadad",
  "T2K4E.Chat.Damage.DamageDealt": "<b>{name}</b> har tillfogat <b>{amount}</b> skada.",
  "T2K4E.Chat.Damage.NoDamageDealt": "Ingen skada tillfogades <b>{name}</b>.",
  "T2K4E.Chat.Damage.InitialAmount": "Attacken gjorde initialt <b>{damage}</b> skada, med en skyddsmodifikation av {mod}.",
  "T2K4E.Chat.Damage.DeflectedDamage": "undvek {damage} skada",
  "T2K4E.Chat.Damage.DeflectedAllDamage": "undvek all skada",
  "T2K4E.Chat.Damage.NoEffect": "ingen effekt",
  "T2K4E.Combat.Attack": "{weapon} — Attack",
  "T2K4E.Combat.Barrier": "Barriär",
  "T2K4E.Combat.BodyArmor": "Kroppsskydd",
  "T2K4E.Combat.NoQuantityLeft": "Inga enheter kvar för vapnet {weapon}.",
  "T2K4E.Combat.NoAmmoLeft": "Ingen ammunition kvar i magasinet för {weapon}.",
  "T2K4E.Combat.NoMag": "Sätt i ett magasiner i vapnet {weapon}.",
  "T2K4E.Dialog.Actions.Normal": "Slå",
  "T2K4E.Dialog.Actions.Reload": "Ladda om",
  "T2K4E.Dialog.Actions.Ok": "OK",
  "T2K4E.Dialog.Actions.Cancel": "Avbryt",
  "T2K4E.Dialog.Roll.Attribute": "Egenskap",
  "T2K4E.Dialog.Roll.Skill": "Färdighet",
  "T2K4E.Dialog.Roll.Formula": "Formel",
  "T2K4E.Dialog.Roll.RoF": "Eldhastighet",
  "T2K4E.Dialog.Roll.Modifier": "Modifierare",
  "T2K4E.Dialog.Roll.Locate": "Lägg till en träfftärning?",
  "T2K4E.Dialog.Roll.MaxPush": "Antal pressanden",
  "T2K4E.Dialog.Roll.RollMode": "Visning",
  "T2K4E.Dialog.CuF.CoolnessUnderFire": "Stridsvana",
  "T2K4E.Dialog.CuF.UnitMorale": "Lägg till Stridsmoralen?",
  "T2K4E.Dialog.Actor.ChooseActor": "Välj en aktör",
  "T2K4E.Dialog.Damage.ChooseDamage": "Amount of Damage",
  "T2K4E.Dialog.Damage.Description": "Choose how much damage to inflict to <b>{target}</b>.",
  "T2K4E.Dialog.Damage.DamageQuantity": "Grundantal",
  "T2K4E.Dialog.Damage.ExtraHits": "Extraträffar",
  "T2K4E.Dialog.Damage.BarrierArmors": "Barriärens skyddsnivå",
  "T2K4E.Dialog.Damage.BarrierArmorsHint": "Multipla barriärer kommasepareras.",
  "T2K4E.Macro.MultipleItems": "Din aktiva aktör {actor} har mer än ett föremål med namnet {item}. Det första matchade objektet kommer att väljas.",
  "T2K4E.Macro.NoItem": "Din aktiva aktör {actor} har inte ett objekt som heter {item}.",
  "SETTINGS.trackPcAmmo.name": "Räkna av spelarnas ammunition",
  "SETTINGS.trackPcAmmo.label": "Huruvida spelarnas ammunition automatiska skall räknas av vid nyttjande.",
  "SETTINGS.trackNpcAmmo.name": "Räkna av SLP:ers ammunition",
  "SETTINGS.trackNpcAmmo.label": "Huruvida spelarnas ammunition automatiska skall räknas av vid nyttjande.",
  "SETTINGS.trackVehicleAmmo.name": "Räkna av fordonsammunition",
  "SETTINGS.trackVehicleAmmo.label": "Huruvida spelarnas ammunition automatiska skall räknas av vid nyttjande.",
  "SETTINGS.showTaskCheckOptions.name": "Fråga om uppdragsval som standard",
  "SETTINGS.showTaskCheckOptions.label": "Håll ned shift för att växla.",
  "SETTINGS.closeRollTooltipDelay.name": "Fördröjning av verktygstips för tärningsslag",
  "SETTINGS.closeRollTooltipDelay.label": "Hur många sekunder skall verktygstipset dröja kvar innan de automatiskt stängs ned. Max är 15 minuter. Sätt detta värde till -1 för att aldrig stängas.",
  "SETTINGS.defaultCharTokenSize.name": "Standard prototypstorlek för SLP:er och rollpersoner",
  "SETTINGS.defaultCharTokenSize.label": "Sett en standard prototypstorlek [0.3, 2.0] för nyskapade SLP:er och rollpersonaktörer.",
  "YZUR.CHAT.ROLL.Push": "Pressa",
  "YZUR.CHAT.ROLL.HitLocation": "Träffområde:",
  "YZUR.CHAT.ROLL.HitLocations": "Träffområden:",
  "YZUR.CHAT.ROLL.Locations.1": "Ben",
  "YZUR.CHAT.ROLL.Locations.2": "Bål",
  "YZUR.CHAT.ROLL.Locations.3": "Bål",
  "YZUR.CHAT.ROLL.Locations.4": "Bål",
  "YZUR.CHAT.ROLL.Locations.5": "Armar",
  "YZUR.CHAT.ROLL.Locations.6": "Huvud",
  "YZUR.CHAT.ROLL.ExtraHit": "Extra träff:",
  "YZUR.CHAT.ROLL.ExtraHits": "Extra träffar:",
  "YZUR.CHAT.ROLL.Suppression": "Nedhållande:",
  "YZUR.CHAT.ROLL.AmmoSpent": "Spenderad ammunition:",
  "YZUR.CHAT.ROLL.DamageOrStress": "Skada/Stress:",
  "YZUR.CHAT.ROLL.JamCount": "Pålitlighet:",
  "YZUR.CHAT.ROLL.Jammed": "VAPENSTOPP!!",
  "YZUR.DIETYPES.D6TwilightDie": "Bas T6",
  "YZUR.DIETYPES.D8TwilightDie": "Bas T8",
  "YZUR.DIETYPES.D10TwilightDie": "Bas T10",
  "YZUR.DIETYPES.D12TwilightDie": "Bas T12",
  "YZUR.DIETYPES.AmmoDie": "Ammunition",
  "YZUR.DIETYPES.LocationDie": "Träfftärning",
  "GAME.Paused": "Kriget pausat",
  "ACTOR.TypeCharacter": "Rollperson",
  "ACTOR.TypeNpc": "Spelledarperson",
  "ACTOR.TypeVehicle": "Fordon",
  "ACTOR.TypeUnit": "Militär enhet",
  "ITEM.TypeWeapon": "Vapen",
  "ITEM.TypeArmor": "Kroppsskydd",
  "ITEM.TypeAmmunition": "Ammunition",
  "ITEM.TypeGrenade": "Sprängämne",
  "ITEM.TypeGear": "Utrustning",
  "ITEM.TypeInjury": "Kritisk skada",
  "ITEM.TypeSpecialty": "Specialitet",
  "EFFECT.StatusFullCover": "Heltäckande skydd",
  "EFFECT.StatusPartialCover": "Partiellt skydd",
  "EFFECT.StatusOverwatch": "Övervakning",
  "EFFECT.StatusSuppressed": "Nedhållande",
  "EFFECT.StatusStop": "Stopp",
  "EFFECT.StatusSmoke": "Rök",
  "EFFECT.StatusFire": "Eld",
  "EFFECT.StatusSlowAction": "Långsam handling spenderad",
  "EFFECT.StatusFastAction": "Snabb handling spenderad"
}
`

**Comment by tinwe** [comment]
Ok, I actually think I managed to commit it now. Check if it's correct.
Sorry for the spam.

**Comment by Stefouch** [comment]
Looks great!
I will merge it for the next update

**Pull request merged**
